[RUSTERS_CORE]
PROJECT_ID="{{ PROJECT_ID }}"
BACKEND_PORT={{ BACKEND_PORT }}
FRONTEND_PORT={{ FRONTEND_PORT }}
ENVIRONMENT="development"
HTTP_SERVER="{{ HTTP_SERVER }}"

[RUSTERS_DATABASE]
CONNECTION_TYPE="{{ DB_DRIVER }}"
SOURCE_PATH="database/project.sqlite"
CREDENTIAL_USER=""
CREDENTIAL_PASS=""
# HOST=localhost
# PORT=3306
# DB_NAME={{ PROJECT_ID }}
